# Numpy: Vectores y Matrices

**Elaborado por:** David Palacio J.  
**Correo:** davidpalacioj@gmail.com

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/dpalacioj/DataAI-Fundamentos-Aplicaciones/blob/main/Analitica/ciencia_datos_con_python/notebooks_teoria/02_numpy_vectores_matrices.ipynb)

---

Numpy es una librería de álgebra lineal para python. La razón por la cual es tan importante para ciencia de datos es que casi todas las librerías del ecosistema de PyData (pandas, tensorflow, pytorch, scipy, scikit-learn, etc.).

Además es una librería eficiente, ya que tiene enlaces a librerías en C. Para obtener información sobre por qué usar Arrays en lugar de listas, puedes remitirte a este enlace: [StackOverflow post.](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists)

## Instrucciones de instalación

Si está usando Google Colab, NumPy está instalado por defecto. En caso de estar usando un IDE como Pycharm o VsCode, en la terminal debes escribir:

`pip install numpy`

## Importando Numpy

Luego de instalar Numpy la librería se importa de la siguiente manera:

In [1]:
# esta es la forma estandar de importar numpy

import numpy as np

In [2]:
np.__version__ # para ver la versión de numpy

'1.23.5'

Numpy tiene muchas funciones integradas. Este tutorial se enfocará en vectores, arreglos, matrices y generación de números.

## Arreglos en Numpy (Arrays)

Los arreglos en NumPy son la principal forma de usar NumPy. Los arreglos de NumPy escencialmente vienen en dos tipos: vectores y matrices.

Los vectores son estrictamente matrices de 1-d y las matrices son 2- (pero debe tener en cuenta que una matriz aún puede tener solo una fila o una columna).

### Crear arreglos de listas de Python

Podemos crear un arreglo mediante la conversión directa de una lista o lista de listas:

In [3]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
type(my_list)

list

In [5]:
np.array(my_list) # se puede asignar a una variable

array([1, 2, 3])

In [6]:
# Puedo asginarlo a una variable

a = np.array(my_list)
type(a)

numpy.ndarray

In [7]:
a.dtype # tipo de datos que están en el arreglo

dtype('int64')

In [8]:
# Una lista de listas

my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix) # Conversión de una listas a Matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b = np.array(my_matrix)

In [11]:
type(b)

numpy.ndarray

### Conclusiones Preliminares

* La diferencia entre una `lista` Python y un `array` de NumPy, es significativa en términos de funcionalidad, rendimiento y uso en la práctica.

**Tipo de dato**

* Una lista en Python es una colección genérica que puede contener elementos de **diferentes tipos**. Por ejemplo: strings, int, float, etc.
* Los elementos de una lista son **objetos** en Python. Esto implica un mayor uso de memoria y menor eficiencia en operaciones numéricas.

* Por su parte, un array de NumPy es una estructura de datos homogénea, es decir, todos sus elementos deben ser del mismo tipo. 
* Los elementos de un array de NumPy se almacenan en un bloque contiguo de memoria, lo que permite operaciones más eficientes.

**Rendimiento**

* Las operaciones en lista de Python son más lentas porque están diseñadas para ser flexibles y manejar cualquier tipo de dato.
* Por ejemplo, sumar dos listas requiere un bucle explícito o el uso de funciones como `map` o `list comprehension`.


* Por su parte, NumPy está optimizado para operaciones numéricas. Las operaciones en arrays de NumPy se ejcutan en tiempo constante y están altamente optimizadas gracias a su implementación en C.
* Por ejemplo, al sumar dos arrays de NumPy es una operación vectorizada que se ejecuta mucho más rápido que en listas de Python.


**Operaciones Vectorizadas**

* La lista de Python no admite operaciones vectorizadas de manera nativa. Por ejemplo, para sumar dos listas elemento por elemento, necesitas usar un bucle o una comprensión de listas.

* Por su parte, un array de NumPy puede realizar operaciones en todo el array sin necesidad de crear bucles explícitos.

In [12]:
# Operaciones vectorizadas en listas

list1 = [1, 2, 3]

list2 = [4, 5, 6]

result = [a + b for a, b in zip(list1, list2)]

print(result) 

[5, 7, 9]


In [14]:
# Operaciones vectorizadas en numpy


array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

result = array1 + array2

print(result)  

[5 7 9]


## Métodos integrados

También conocido como `built-in methods` son funciones que vienen incluidas en el propio lenguajde Python, sin necesidad de importar bibliotecas adicionales.

Veamos algunos:

### arange

In [16]:
# Generar un arreglo de enteros desde 0 hasta 9
# recordar que el valor final no se incluye

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# valor_inicial, valor_final-1, paso

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros y ones

In [19]:
# útil para generar arreglos de ceros o unos

np.zeros(3)

array([0., 0., 0.])

In [20]:
# Generar una matriz de ceros de 5 x 5 elementos

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
# Generar una matriz de unos 5 x 5 elementos

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Devuelve números espaciados uniformemente durante un intervalo definido

In [22]:
# Generar 3 valores iniciando en 0 y terminando en 10
# linspace(valor_inicial, valor_final, cantidad_de_valores)

np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

### eye

Crea la matriz identidad

In [23]:
# crear la matriz identidad de 4x4 elementos

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Números aleatorios

Numpy tiene diferentes formas de crear arreglos de números aleatorios. El módulo para realizar esto se llama Random.

#### rand

Crea un arreglo de la forma dada y la rellena con muestras aleatorias de una distribución uniforme sobre [0, 1].

In [24]:
# creación de un arreglo de 2 elementos de 1 dimensión

np.random.rand(2)

array([0.18173703, 0.11959571])

#### randint

Entrega números enteros aleatorios.

In [25]:
np.random.randint(1, 100)

81

In [26]:
np.random.randint(1, 100, (10, 2))

array([[83, 26],
       [25, 39],
       [97, 12],
       [93, 77],
       [70,  2],
       [81, 54],
       [48, 38],
       [76, 80],
       [42, 40],
       [44, 89]])

## Atributos y métodos de los arreglos

In [ ]:
arreglo = np.arange(25)
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([34, 38, 13,  9, 47,  5, 22, 28,  1, 17])

### reshape

Devuelve una matriz que contiene los mismos datos con una nueva distribución.

In [29]:
# arreglo es un vector de 25 elementos
# y se convertirá en una matriz de 5x5 elementos

arreglo.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice de su ubicación usando argmin o argmax.

In [31]:
ranarr

array([34, 38, 13,  9, 47,  5, 22, 28,  1, 17])

In [32]:
# valor máximo del arreglo
ranarr.max()

47

In [33]:
# posición del valor máximo del arreglo

ranarr.argmax()

4

In [35]:
# valor mínimo del arreglo

ranarr.min()

1

In [34]:
# valor mínimo del arreglo

ranarr.argmin()

8

### shape

Shape es un atributo que los arreglos tienen para definir sus dimensiones (no es un método).

In [37]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
arreglo.shape

(25,)

In [41]:
# cambiemos las dimensiones del arreglo para que sea una matriz

arreglo.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
arreglo.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype

Para obtener los tipos de datos dentro del arreglo:

In [45]:
arreglo.dtype

dtype('int64')

### size

Número de elementos de un arreglo

In [46]:
arreglo.size

25

In [49]:
arreglo_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arreglo_2d.size

9

In [51]:
arreglo_2d.shape

(3, 3)

In [ ]:
arreglo_2d.ndim # Dice si el arreglo es un vector, una matriz o un cubo

2

## Indexación y Selección con corchetes

In [52]:
arreglo

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
arreglo[1]

1

In [54]:
arreglo[2:5]

array([2, 3, 4])

### ¿Qué resultado da `arreglo[1:-9]`?

In [56]:
arreglo[1:-9]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Concatenación

La función `np.concatenate` se usa para unir dos o más arrays a lo largo de un eje especificado. Si no se especifica el eje, por defecto se concatena a lo largo del **primer eje** (axis=0), que en un array 2D corresponde a las filas.

In [57]:
# En una dimension
x = np.array([1, 2, 3])  # Vector de valores
y = np.array([3, 2, 1])  # Vector de valores
np.concatenate([x, y])  # Concatenación

array([1, 2, 3, 3, 2, 1])

In [65]:
# En dos dimensiones de forma vertical
grid = np.array([[1, 2, 3], [4, 5, 6]])
print(grid)
print("----")
print(np.concatenate([grid, grid], axis=0))  # Concatenación
print("----")
print(np.concatenate([grid, grid], axis=1))


[[1 2 3]
 [4 5 6]]
----
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
----
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Operaciones con Numpy

Con las listas de Python no se pueden realizar operaciones elemento a elemento, pero con NumPy si se puede realizar.

In [67]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
lista + lista # Esto lo que hace es concatenar las listas

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
x = 2

lista * x # Esto lo que hace es repetir la lista x veces

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Si quiero realizar operaciones vectoriales o con matrices se realizan con arreglos NumPy.**

## Aritmética

In [71]:
arreglo = np.arange(0, 10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arreglo + arreglo

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Lecturas sugeridas

Numpy tiene integrado muchas funciones universales, que son escencialmente solo operaciones matemáticas que se pueden usar para realizar la operación en todo el arreglo. Las más importantes son:

* [Matemáticas](https://numpy.org/doc/stable/reference/ufuncs.html#math-operations)
* [Trignometría](https://numpy.org/doc/stable/reference/ufuncs.html#trigonometric-functions)
* [Funciones de comparación](https://numpy.org/doc/stable/reference/ufuncs.html#comparison-functions)

# Referencias

* [Tutorial oficial de NumPy](https://numpy.org/doc/stable/user/quickstart.html)
* [NumPy Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
* [Ciencia de datos con NumPy](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)